import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import PersistentPlayer from "@/components/PersistentPlayer";
import dynamic from "next/dynamic";
import Link from "next/link";

const AudioPlayerProvider = dynamic(() => import("@/context/ContextProvider"), {
  ssr: false,
});

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AudioPlayerProvider>
          <div className="w-full h-12 m-4 ">
            <ul className="flex gap-4">
              <li className="font-bold border-2 p-2">
                <Link href="/">Home</Link>
              </li>
              <li className="font-bold border-2 p-2">
                <Link href="/about">About</Link>
              </li>
              <li className="font-bold border-2 p-2">
                <Link href="/contact">Contact</Link>
              </li>
            </ul>
          </div>
          {children}
          <PersistentPlayer />
        </AudioPlayerProvider>
      </body>
    </html>
  );
}
